#include <array>
#include <cmath>
#include <vector>

#include <charconv>
#include <fstream>
#include <iostream>
#include <ranges>
#include <sstream>
#include <string>
#include <random>

#include "tgaimage.h"

#include "canvas.h"
#include "model.h"
#include "our_gl.h"
#include "shaders.h"

int main(int argc, char** argv) {
	using namespace Canvas;

	std::vector<Model> scene_models;
	scene_models.emplace_back("diablo3_pose");
	scene_models.emplace_back("floor");

	// main camera
	RenderContext rContext{};
	rContext.lookat(eye, center, up);
	rContext.init_perspective(norm(eye - center));
	rContext.init_viewport(width / 16, height / 16, width * 7 / 8, height * 7 / 8);
	TGAImage finalbuffer(width, height, TGAImage::RGB);
	std::vector<double> total_occlusion_buffer(width * height); // shadow buff from CAMERA POV

	RenderContext shContext{}; // holds viewing context from Light POV and light's zbuffer / shadow buffer
	shContext.init_viewport(width / 16, height / 16, width * 7 / 8, height * 7 / 8);
	TGAImage shadowbuffer(width, height, TGAImage::GRAYSCALE); // shadow buff from LIGHT POV, holds 2D zbuffer generated by light
	std::mt19937 mt{ 10 };
	std::uniform_real_distribution<double> getX{ 0., 1. };
	std::uniform_real_distribution<double> getY{ 0.5, 1. };
	constexpr int iterations{ 1000 };
	vec4 world_light{ 0, 0, 0, 0 };
	for (int c{ 0 }; c < iterations; ++c) {
		world_light.x = getX(mt);
		world_light.y = getY(mt);
		world_light.z = getX(mt);
		shContext.lookat(world_light.xyz(), center, up);
		shContext.init_perspective(norm(world_light.xyz() - center));
		shContext.init_zbuffer();
		for (const auto& model : scene_models) {
			ShadowShader shadow(model, shContext);
			for (int f{ 0 }; f < model.nfaces(); ++f) {
				Triangle triang_vertices{
					shadow.vertex(f, 0),
					shadow.vertex(f, 1),
					shadow.vertex(f, 2),
				};

				shContext.rasterize(triang_vertices, shadow, shadowbuffer);
			}
		}

		// reset new frame buffer (filled with blacks / 0)
		TGAImage tmp_framebuffer(width, height, TGAImage::GRAYSCALE); // temp b&w image from CAMERA POV for one light position
		// reset camera POV's zbuffer for this new image (bc we have a new light POV)
		rContext.init_zbuffer();

		for (const auto& model : scene_models) {
			PhongShader phong(model, rContext, shContext, world_light);
			for (int f{ 0 }; f < model.nfaces(); ++f) {
				Triangle triang_vertices{
					phong.vertex(f, 0),
					phong.vertex(f, 1),
					phong.vertex(f, 2)
				};

				rContext.rasterize(triang_vertices, phong, tmp_framebuffer);
			}
		}
#pragma omp parallel for
		for (std::size_t x{ 0 }; x < width; ++x) {
			for (std::size_t y{ 0 }; y < height; ++y) {
				total_occlusion_buffer[x + y * width] += tmp_framebuffer.get(x, y)[0];
			}
		}
	}

	// average each points shadow "intensity" from all shadow maps
	for (int i{ 0 }; i < total_occlusion_buffer.size(); ++i) {
		total_occlusion_buffer[i] /= iterations;
	}


	// final render pass, with averaged shadow intensity
	rContext.init_zbuffer();
	shContext.zbuffer = total_occlusion_buffer; // dont care about light coords, shContext holds one important field: zbuffer
	for (const auto& model : scene_models) {
		PhongShader phong(model, rContext, shContext, world_light);
		for (int f{ 0 }; f < model.nfaces(); ++f) {
			Triangle triang_vertices{
				phong.vertex(f, 0),
				phong.vertex(f, 1),
				phong.vertex(f, 2)
			};

			rContext.rasterize(triang_vertices, phong, finalbuffer);
		}
	}

	finalbuffer.write_tga_file("framebuffer.tga");
	return 0;
}
