#include <array>
#include <cmath>
#include <vector>

#include <charconv>
#include <fstream>
#include <iostream>
#include <ranges>
#include <sstream>
#include <string>
#include <random>
#include <numbers>

#include "tgaimage.h"

#include "canvas.h"
#include "model.h"
#include "our_gl.h"
#include "shaders.h"

int main(int argc, char** argv) {
	using namespace Canvas;

	std::vector<Model> scene_models;
	scene_models.emplace_back("diablo3_pose");
	scene_models.emplace_back("floor");


	// main camera
	RenderContext rContext{};
	rContext.lookat(eye, center, up);
	rContext.init_perspective(norm(eye - center));
	rContext.init_viewport(width / 16, height / 16, width * 7 / 8, height * 7 / 8);
	rContext.init_zbuffer(width, height);
	TGAImage finalbuffer(width, height, TGAImage::RGB);
	std::vector<double> total_occlusion_buffer(width * height); // shadow buff from CAMERA POV

	// one render to freeze zbuffer from camera pov (zbuffer will never change for that)
	for (const auto& model : scene_models) {
		ShadowShader firstRenderShader(model, rContext);
		for (int f{ 0 }; f < model.nfaces(); ++f) {
			Triangle triang_vertices{
				firstRenderShader.vertex(f, 0),
				firstRenderShader.vertex(f, 1),
				firstRenderShader.vertex(f, 2)
			};

			rContext.rasterize(triang_vertices, firstRenderShader, finalbuffer);
		}
	}

	/*
	1000 times:
	- render from random light
	- this render fills shContext.zbuffer
	- for each camera pixel, unproject it into model space, then project that into light view
	- if shContext.zbuffer > Z, add 1 to visibility, else it is behind an object!
	*/

	RenderContext shContext{}; // holds viewing context from Light POV and light's zbuffer / shadow buffer
	constexpr int shadoww{ 8000 };
	constexpr int shadowh{ 8000 };
	shContext.init_viewport(shadoww / 16, shadowh / 16, shadoww * 7 / 8, shadowh * 7 / 8);
	TGAImage trash(shadoww, shadowh, TGAImage::GRAYSCALE); // shadow buff from LIGHT POV, holds 2D zbuffer generated by light

	// unproject camera -> model space
	const matrix<4, 4> camera_to_model{ (rContext.Viewport * rContext.Perspective * rContext.ModelView).inverse() };


	// randomizer stuff
	std::mt19937 mt{ 10 };
	/*
	dA = (r * sintheta * dtheta) * dphi		-> phi is rotation around horizontal, theta polar angle
	but y = r * costheta
	dy = -sintheta * dtheta
	ignoring - sign
	dA = dy * dphi
	*/
	constexpr double PI{ std::numbers::pi };
	std::uniform_real_distribution<double> getY{ 0., 1. };
	std::uniform_real_distribution<double> getPhi{ 0, 2 * PI };
	vec4 world_light{ 0, 0, 0, 0 };

	constexpr int iterations{ 400 };
	for (int c{ 0 }; c < iterations; ++c) {
		const double phi{ getPhi(mt) };
		world_light.y = getY(mt);

		const double r{ std::sqrt(1 - world_light.y * world_light.y) };
		world_light.x = std::cos(phi) * r;
		world_light.z = std::sin(phi) * r;
		world_light *= 1.5; // ensure light camera is further away than model space

		shContext.lookat(world_light.xyz(), center, up);
		shContext.init_perspective(norm(world_light.xyz() - center));
		shContext.init_zbuffer(shadoww, shadowh);
		for (const auto& model : scene_models) {
			ShadowShader shadow(model, shContext);
			for (int f{ 0 }; f < model.nfaces(); ++f) {
				Triangle triang_vertices{
					shadow.vertex(f, 0),
					shadow.vertex(f, 1),
					shadow.vertex(f, 2),
				};

				shContext.rasterize(triang_vertices, shadow, trash);
			}
		}

		// viewport matrix included here (not waiting to normalize clip space -> ndc b4 applying viewport)
		// bc math comes out the same (1/w is a scalar, commutative)
		const matrix<4, 4> model_to_light{ shContext.Viewport * shContext.Perspective * shContext.ModelView * camera_to_model };

#pragma omp parallel for
		for (std::size_t x{ 0 }; x < width; ++x) {
			for (std::size_t y{ 0 }; y < height; ++y) {
				double cam_z{ rContext.zbuffer[x + y * width] };
				if (cam_z < -1e5) {
					// It's empty sky/background: nothing occludes / blocks it
					total_occlusion_buffer[x + y * width] += 1;
					continue;
				}

				vec4 camera_coords{ x, y, cam_z, 1. };

				// convert light shader from eye space -> object/model space 
				// -> light space -> light Clip space (perspective, but not inside [-1, 1] cube)
				// -> viewport space (2D)
				vec4 coords_light_pov{ model_to_light * camera_coords };

				// perspective divide to get actual 2D screen coordinates
				vec4 screen_light{ coords_light_pov / coords_light_pov.w };

				int shX{ static_cast<int>(screen_light.x) }, shY{ static_cast<int>(screen_light.y) };
				double shZ{ screen_light.z };

				constexpr double shadow_bias{ 0.03 };

				// if inside shadow map bounds
				if (shX >= 0 && shX < shadoww && shY >= 0 && shY < shadowh) {
					// shContext.zbuffer holds what the light saw
					// shX, Y, Z are the values from the fragment (object space) -> light space
					// if the fragment happens to be BEHIND what the light saw, it is in_shadow
					if (shZ + shadow_bias >= shContext.zbuffer[shX + shY * shadoww]) {
						total_occlusion_buffer[x + y * width] += 1;
					}
				}
			}
		}
	}

	// average each points shadow "intensity" from all shadow maps
	for (int i{ 0 }; i < total_occlusion_buffer.size(); ++i) {
		total_occlusion_buffer[i] /= iterations;
	}


	// final render pass, with averaged shadow intensity
	rContext.init_zbuffer(width, height);
	shContext.zbuffer = total_occlusion_buffer; // dont care about light coords, shContext holds one important field: zbuffer
	for (const auto& model : scene_models) {
		PhongShader phong(model, rContext, shContext, world_light);
		for (int f{ 0 }; f < model.nfaces(); ++f) {
			Triangle triang_vertices{
				phong.vertex(f, 0),
				phong.vertex(f, 1),
				phong.vertex(f, 2)
			};

			rContext.rasterize(triang_vertices, phong, finalbuffer);
		}
	}

	finalbuffer.write_tga_file("framebuffer.tga");
	return 0;
}
